---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: yeti
---

```{r setup, include=FALSE}
# Importing libraries
library(flexdashboard)
library(tidyverse)
library(highcharter)
library(gt)
library(htmltools)
library(viridis)
```

```{r}
# import data
df <- read_csv('bestsellers with categories.csv', show_col_types = FALSE)

# remove duplicates
df <- df %>%
  distinct(Name, .keep_all = TRUE) %>%
  rename(User_Rating = 'User Rating')

```

Books
=====================================


Column {.tabset .tabset-fade data-width=650}
-----------------------------------------------------------------------

### Most Popular Authors

```{r}

# Colors
custom_colors <- viridis::mako(n = 15)
# names(df)
# df$Author <- as.character(df$Author)
df$Author <- as.factor(df$Author)
# unique(df$Author)  # Check unique values

# Most Popular by reviews
df %>%
  group_by(Author) %>%
  summarise(Reviews = mean(Reviews)) %>%
  arrange(desc(Reviews)) %>%
  head(15) %>%
  hchart('column', hcaes(x = Author, y = Reviews, color = custom_colors)) %>%
  hc_add_theme(hc_theme_google()) %>%
  hc_tooltip(pointFormat = '<b> Number of Reviews: </b> {point.y} <br>') %>%
  hc_title(
    text = 'Most Popular Authors from 2009 to 2019',
    style = list(
      fontSize = '25px',
      fontWeight = 'bold'
    )
  ) %>%
  hc_subtitle(
    text = 'By Number of Reviews',
    style = list(
      fontSize = '16px'
    )
  ) %>%
  hc_credits(enabled = TRUE, text = '@miguelfzzz')



```

### Most Popular Books

```{r}

custom_colors <- viridis::plasma(n = 15)

df %>%
  arrange(desc(Reviews)) %>%
  head(15) %>%
  hchart('bar', hcaes(x = Name, y = Reviews, color = custom_colors )) %>%
  hc_add_theme(hc_theme_google()) %>%
  hc_tooltip(pointFormat = '<b> Number of Reviews </b> {point.y} <br>') %>%
  hc_title(
    text = 'Most Popular Books from 2009 to 2019',
    style = list(
      fontSize  = '25px',
      fontWeight = 'bold'
    )
  ) %>%
  hc_subtitle(
    text = 'By Number of Reviews',
    style = list(
      fontSize  = '16px'
    )
  ) %>%
  hc_credits(enabled = TRUE, text = '@miguelfzzz')
```

Column {data-width=350}
-----------------------------------------------------------------------

### {.no-padding}

```{r}
# Colors

custom_colors = viridis::mako(n = 2)

# Most Common genre

# names(df)
# df$Genre <- as.character(df$Genre)
df$Author <- as.factor(df$Author)
# unique(df$Author)  # Check unique values
df %>%
  group_by(Genre) %>%
  summarise(count = n()) %>%
  hchart('pie', hcaes(x = Genre, y = count, color = custom_colors)) %>%
  hc_add_theme(hc_theme_google()) %>%
  hc_tooltip(pointFormat = '<b> Proportion:  </b> {point.percentage:,.2f}%' ) %>%
  hc_title(
    text = 'Most Common Genre from 2009 to 2019',
    style = list(
      fontSize  = '15px',
      fontWeight = 'bold'
    )
  ) %>%
  hc_credits(enabled = TRUE, text = '@miguelfzzz')

  
  

```

### {.no-padding}

```{r}

df1 <- df %>%
  filter(User_Rating >= 4.9) %>%
  arrange(desc(Reviews)) %>%
  select(Name, Author)

# HTML Table

div(
  style = 'height : 600px;overflow-y:scroll',
  gt(df1) %>%
  tab_header(
    title = md('Best Book from 2009 to 2019'),
    subtitle = md('By User Rating')
  ) %>%
  opt_table_font(
    font = list(
      google_font('Chivo'),
      default_fonts()
    )
  ) %>%
  tab_style(
    locations = cells_column_labels(
      columns = everything()
    ),
    style = list(
      cell_borders(
        sides = 'bottom',
        weight = px(2),
        cell_text(weight = 'bold')
      )
    )
  ) %>%
  tab_options(
    table.font.size = px(12L),
    table.border.top.style = 'none',
    column_labels.border.bottom.width = 'none',
    data_row.padding = px(3)
  )
)

```


```{r}
# import second data
data <- read_csv('charts.csv', show_col_types = FALSE)


data <- data %>%
  
  rename(
    weeks_on_board = 'weeks-on-board',
    peak_rank = 'peak-rank'
  ) %>%
  
  select(-'last-week')
  
# removing duplicate

# data1 <- data %>%
#   
#   group_by(song, artist) %>%
#   
#   summarise(weeks_on_board = max(weeks_on_board))

data1 <- data %>%
  group_by(song, artist) %>%
  summarise(weeks_on_board = max(weeks_on_board), .groups = "drop")



```
Songs
========================================================================

Column (data-width = 350)
--------------------------------------------------------------------

### Most Popular Songs in BillBoard

```{r}

#colors

custom_colors = viridis::mako(n = 20)

data1 %>%
  arrange(desc(weeks_on_board)) %>%
  head(20) %>%
  hchart(
    'lollipop',
    hcaes(
      x = song, 
      y = weeks_on_board, 
      color = custom_colors
    )
  ) %>%
  hc_add_theme(hc_theme_google())  %>%
  hc_tooltip(pointFormat = '<b> Number of Weeks on board</b> {point.y} <br>') %>%
  hc_yAxis(
    title = list(
      text = list(
        text = 'Weeks on Board'
      )
    )
  ) %>%
  hc_title(
    text = 'Most Popular Songs',
    style = list(
      fontSize = '25px',
      fontWeight = 'bold'  
    )
  ) %>%
  
  hc_subtitle(
    text = 'By Number of Weeks on Board:',
    style = list(
      fontSize = '16px'
    )
  ) %>%
  
  hc_credits(enabled = TRUE, text = '@miguelfzzz')
  
```

Column (data-width = 200)
--------------------------------------------------------------------

### Most Popular Artists in Billboard

```{r}

# Colors
custom_colors <- viridis::plasma(n = 10)

data1 %>%
  group_by(artist) %>%
  summarise(weeks_on_board = sum(weeks_on_board)) %>%
  arrange(desc(weeks_on_board)) %>%
  head(10) %>%
  
  hchart('pie', hcaes(x = artist, y = weeks_on_board, color = custom_colors)) %>%
  hc_add_theme(hc_theme_google()) %>%
  
  hc_tooltip(pointFormat = '<b> Number of Weeks on Board:</b> {point.y} <br>') %>%
  
  hc_subtitle(
    text = 'By Number of Weeks on Board',
    style = list(
      fontSize = '16px'
    )
  ) %>%
  
  hc_credits(enabled = TRUE, text = '@miguelfzzz')

```

